/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T17:21:20Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPhotosResponse
 */
export interface GetPhotosResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPhotosResponse
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetPhotosResponse
     */
    labels?: Array<string>;
}

/**
 * Check if a given object implements the GetPhotosResponse interface.
 */
export function instanceOfGetPhotosResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPhotosResponseFromJSON(json: any): GetPhotosResponse {
    return GetPhotosResponseFromJSONTyped(json, false);
}

export function GetPhotosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPhotosResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
    };
}

export function GetPhotosResponseToJSON(value?: GetPhotosResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'labels': value.labels,
    };
}

