/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T19:00:42Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProjectsResponsePhotosInner
 */
export interface GetProjectsResponsePhotosInner {
    /**
     * 
     * @type {number}
     * @memberof GetProjectsResponsePhotosInner
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    consumerID?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    purchaseID?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    time?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    producerID?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    projectID?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProjectsResponsePhotosInner
     */
    tags?: string;
}

/**
 * Check if a given object implements the GetProjectsResponsePhotosInner interface.
 */
export function instanceOfGetProjectsResponsePhotosInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProjectsResponsePhotosInnerFromJSON(json: any): GetProjectsResponsePhotosInner {
    return GetProjectsResponsePhotosInnerFromJSONTyped(json, false);
}

export function GetProjectsResponsePhotosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsResponsePhotosInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'consumerID': !exists(json, 'consumerID') ? undefined : json['consumerID'],
        'purchaseID': !exists(json, 'purchaseID') ? undefined : json['purchaseID'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'producerID': !exists(json, 'producerID') ? undefined : json['producerID'],
        'projectID': !exists(json, 'projectID') ? undefined : json['projectID'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function GetProjectsResponsePhotosInnerToJSON(value?: GetProjectsResponsePhotosInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'filename': value.filename,
        'consumerID': value.consumerID,
        'purchaseID': value.purchaseID,
        'time': value.time,
        'producerID': value.producerID,
        'projectID': value.projectID,
        'tags': value.tags,
    };
}

