/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T00:26:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPhotosProducerResponsePhotosListInner
 */
export interface GetPhotosProducerResponsePhotosListInner {
    /**
     * 
     * @type {number}
     * @memberof GetPhotosProducerResponsePhotosListInner
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof GetPhotosProducerResponsePhotosListInner
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPhotosProducerResponsePhotosListInner
     */
    time?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetPhotosProducerResponsePhotosListInner
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the GetPhotosProducerResponsePhotosListInner interface.
 */
export function instanceOfGetPhotosProducerResponsePhotosListInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPhotosProducerResponsePhotosListInnerFromJSON(json: any): GetPhotosProducerResponsePhotosListInner {
    return GetPhotosProducerResponsePhotosListInnerFromJSONTyped(json, false);
}

export function GetPhotosProducerResponsePhotosListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPhotosProducerResponsePhotosListInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function GetPhotosProducerResponsePhotosListInnerToJSON(value?: GetPhotosProducerResponsePhotosListInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'filename': value.filename,
        'time': value.time,
        'tags': value.tags,
    };
}

