/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T01:31:50Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetPhotosProducerResponsePhotosListInner } from './GetPhotosProducerResponsePhotosListInner';
import {
    GetPhotosProducerResponsePhotosListInnerFromJSON,
    GetPhotosProducerResponsePhotosListInnerFromJSONTyped,
    GetPhotosProducerResponsePhotosListInnerToJSON,
} from './GetPhotosProducerResponsePhotosListInner';

/**
 * 
 * @export
 * @interface GetPhotosProducerResponse
 */
export interface GetPhotosProducerResponse {
    /**
     * 
     * @type {Array<GetPhotosProducerResponsePhotosListInner>}
     * @memberof GetPhotosProducerResponse
     */
    photosList?: Array<GetPhotosProducerResponsePhotosListInner>;
}

/**
 * Check if a given object implements the GetPhotosProducerResponse interface.
 */
export function instanceOfGetPhotosProducerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPhotosProducerResponseFromJSON(json: any): GetPhotosProducerResponse {
    return GetPhotosProducerResponseFromJSONTyped(json, false);
}

export function GetPhotosProducerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPhotosProducerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'photosList': !exists(json, 'photos_list') ? undefined : ((json['photos_list'] as Array<any>).map(GetPhotosProducerResponsePhotosListInnerFromJSON)),
    };
}

export function GetPhotosProducerResponseToJSON(value?: GetPhotosProducerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'photos_list': value.photosList === undefined ? undefined : ((value.photosList as Array<any>).map(GetPhotosProducerResponsePhotosListInnerToJSON)),
    };
}

