/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T17:45:27Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPhotosResponseResultsInner
 */
export interface GetPhotosResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof GetPhotosResponseResultsInner
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPhotosResponseResultsInner
     */
    labels?: string;
}

/**
 * Check if a given object implements the GetPhotosResponseResultsInner interface.
 */
export function instanceOfGetPhotosResponseResultsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPhotosResponseResultsInnerFromJSON(json: any): GetPhotosResponseResultsInner {
    return GetPhotosResponseResultsInnerFromJSONTyped(json, false);
}

export function GetPhotosResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPhotosResponseResultsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
    };
}

export function GetPhotosResponseResultsInnerToJSON(value?: GetPhotosResponseResultsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'labels': value.labels,
    };
}

