/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T19:00:42Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutProjectsRequest
 */
export interface PutProjectsRequest {
    /**
     * 
     * @type {string}
     * @memberof PutProjectsRequest
     */
    photoID?: string;
    /**
     * 
     * @type {string}
     * @memberof PutProjectsRequest
     */
    projectID?: string;
}

/**
 * Check if a given object implements the PutProjectsRequest interface.
 */
export function instanceOfPutProjectsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutProjectsRequestFromJSON(json: any): PutProjectsRequest {
    return PutProjectsRequestFromJSONTyped(json, false);
}

export function PutProjectsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutProjectsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'photoID': !exists(json, 'photoID') ? undefined : json['photoID'],
        'projectID': !exists(json, 'projectID') ? undefined : json['projectID'],
    };
}

export function PutProjectsRequestToJSON(value?: PutProjectsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'photoID': value.photoID,
        'projectID': value.projectID,
    };
}

