/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-12-20T18:15:53Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutUserInfoRequest
 */
export interface PutUserInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    last?: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    projectID?: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    first?: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserInfoRequest
     */
    aboutme?: string;
}

/**
 * Check if a given object implements the PutUserInfoRequest interface.
 */
export function instanceOfPutUserInfoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutUserInfoRequestFromJSON(json: any): PutUserInfoRequest {
    return PutUserInfoRequestFromJSONTyped(json, false);
}

export function PutUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutUserInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'last': !exists(json, 'last') ? undefined : json['last'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'projectID': !exists(json, 'projectID') ? undefined : json['projectID'],
        'first': !exists(json, 'first') ? undefined : json['first'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'aboutme': !exists(json, 'aboutme') ? undefined : json['aboutme'],
    };
}

export function PutUserInfoRequestToJSON(value?: PutUserInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last': value.last,
        'title': value.title,
        'projectID': value.projectID,
        'first': value.first,
        'email': value.email,
        'aboutme': value.aboutme,
    };
}

