name: Pull Request Checks

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install Node Dependencies
        run: |
          pnpm install

      - name: Lint
        working-directory: web
        run: |
          pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install Node Dependencies
        run: |
          pnpm install
          pnpm add -g aws-cdk

      - name: Web Testing
        working-directory: web
        run: |
          pnpm test

      - name: CDK Synth
        run: |
          cdk synth

  style:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install Node Dependencies
        run: |
          pnpm add -g prettier

      - name: Prettier Stylechecks
        run: |
          prettier --check web
          prettier --check stack
