name: Pull Request

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml')
            }}-pr-lint
          restore-keys: |
            ${{ runner.os }}-pnpm-store-pr-lint

      - name: Install Node Dependencies
        run: |
          pnpm install

      - name: Lint
        working-directory: web
        run: |
          pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml')
            }}-pr-test
          restore-keys: |
            ${{ runner.os }}-pnpm-store-pr-test

      - name: Install Node Dependencies
        run: |
          pnpm install
          pnpm add -g aws-cdk

      - name: Web Testing
        working-directory: web
        run: |
          pnpm test

      - name: CDK Synth
        run: |
          cdk synth

  style:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml')
            }}-pr-style
          restore-keys: |
            ${{ runner.os }}-pnpm-store-pr-style

      - name: Install Node Dependencies
        run: |
          pnpm add -g prettier

      - name: Prettier Stylechecks
        run: |
          prettier --check web
          prettier --check stack

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key:
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml')
            }}-pr-build
          restore-keys: |
            ${{ runner.os }}-pnpm-store-pr-build

      - name: Install Node Dependencies
        run: |
          pnpm install --prod

      - name: Web Building
        working-directory: web
        run: |
          pnpm build
