openapi: '3.0.1'
info:
  title: 'Api'
  version: '2022-11-22T20:07:22Z'
servers:
  - url: 'https://gwdg53v8m4.execute-api.us-east-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: 'prod'
paths:
  /photos:
    get:
      responses:
        '200':
          description: '200 response'
          content: {}
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
components:
  securitySchemes:
    DevelopmentLabelHubBackendApiAuthorizerF478BBAE:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'cognito_user_pools'
