openapi: '3.0.1'
info:
  title: 'Api'
  version: '2022-12-20T19:00:42Z'
servers:
  - url: 'https://gwdg53v8m4.execute-api.us-east-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: '/prod'
paths:
  /projects:
    get:
      parameters:
        - name: 'project-id'
          in: 'query'
          required: true
          schema:
            type: 'string'
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProjectsResponse'
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    put:
      parameters:
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutProjectsRequest'
        required: true
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content: {}
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /buy:
    get:
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content: {}
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /photos:
    get:
      parameters:
        - name: 'labels'
          in: 'query'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPhotosResponse'
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /photos/producer:
    get:
      parameters:
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
        - name: 'amount-low'
          in: 'query'
          schema:
            type: 'string'
        - name: 'label'
          in: 'query'
          schema:
            type: 'string'
        - name: 'month'
          in: 'query'
          schema:
            type: 'string'
        - name: 'amount-high'
          in: 'query'
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPhotosProducerResponse'
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /photos/upload:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutPhotoRequest'
        required: true
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutPhotoResponse'
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /income:
    get:
      parameters:
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIncomeResponse'
      security:
        - DevelopmentLabelHubBackendApiAuthorizerF478BBAE: []
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /download:
    get:
      parameters:
        - name: 'project-id'
          in: 'query'
          required: true
          schema:
            type: 'string'
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDownloadResponse'
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
  /userinfo:
    get:
      parameters:
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserInfoResponse'
    put:
      parameters:
        - name: 'access-token'
          in: 'header'
          required: true
          schema:
            type: 'string'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserInfoRequest'
        required: true
      responses:
        '200':
          description: '200 response'
          headers:
            access-control-allow-origin:
              schema:
                type: 'string'
          content: {}
    options:
      responses:
        '204':
          description: '204 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
            Access-Control-Allow-Methods:
              schema:
                type: 'string'
            Access-Control-Allow-Headers:
              schema:
                type: 'string'
          content: {}
components:
  schemas:
    PutPhotoRequest:
      type: 'object'
      properties:
        file:
          type: 'string'
        filename:
          type: 'string'
        id_token:
          type: 'string'
        labels:
          type: 'array'
          items:
            type: 'string'
    PutProjectsRequest:
      type: 'object'
      properties:
        photoID:
          type: 'string'
        projectID:
          type: 'string'
    GetIncomeResponse:
      type: 'object'
      properties:
        income:
          type: 'number'
    PutPhotoResponse:
      type: 'object'
      properties:
        message:
          type: 'string'
    GetDownloadResponse:
      type: 'array'
      items:
        type: 'string'
    GetPhotosResponse:
      type: 'object'
      properties:
        results:
          type: 'array'
          items:
            type: 'object'
            properties:
              url:
                type: 'string'
              labels:
                type: 'string'
    PutUserInfoRequest:
      type: 'object'
      properties:
        last:
          type: 'string'
        title:
          type: 'string'
        projectID:
          type: 'string'
        first:
          type: 'string'
        email:
          type: 'string'
        aboutme:
          type: 'string'
    GetProjectsResponse:
      type: 'object'
      properties:
        photos:
          type: 'array'
          items:
            type: 'object'
            properties:
              amount:
                type: 'number'
              filename:
                type: 'string'
              consumerID:
                type: 'string'
              purchaseID:
                type: 'string'
              time:
                type: 'string'
              producerID:
                type: 'string'
              projectID:
                type: 'string'
              tags:
                type: 'string'
    GetPhotosProducerResponse:
      type: 'array'
      items:
        type: 'object'
        properties:
          amount:
            type: 'number'
          filename:
            type: 'string'
          time:
            type: 'string'
          tags:
            type: 'array'
            items:
              type: 'string'
    GetUserInfoResponse:
      type: 'object'
      properties:
        last_name:
          type: 'string'
        id:
          type: 'string'
        title:
          type: 'string'
        first_name:
          type: 'string'
        projectID:
          type: 'string'
        email:
          type: 'string'
        aboutme:
          type: 'string'
  securitySchemes:
    DevelopmentLabelHubBackendApiAuthorizerF478BBAE:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'cognito_user_pools'
